## In this notebook, we test the model (which was trained on _Corpus Nummorum_ data) on three _Numismatics_ datasets (Seleucid, BIGR, and PELLA)

Plan of attack
* Downloading fine-tuned ImageNet 21k model checkpoint from .pth file
* Saving image and motif metadata for three additional datasets
* Checking the contents of the saved files
* Testing the model on the new datasets using the checkpoint .pth file
* Recording average precision (AP) for each motif and mean average precision (mAP) for each of the three datasets

Import statements and necessary functions

In [ ]:
# from google.colab import runtime
# runtime.unassign()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import sys
sys.path.append('/content/drive/MyDrive/coins_project/')
from utils import *

Investigating .tar file of Corpus Nummorum images

In [ ]:
tar_path = "/content/drive/MyDrive/coins_project/coin_images.tar"

with tarfile.open(tar_path, "r:*") as tar:
    tar.list()

Streaming output truncated to the last 5000 lines.
?rw------- root/root      21378 2026-06-16 10:54:31 ./wreath/CN_type_20079_BNF_41767911_cn_coin_23314_o_obv.jpg
?rw------- root/root      15995 2026-06-16 10:54:31 ./wreath/CN_type_20079_MK_242_cn_coin_45896_p_obv.jpg
?rw------- root/root      22313 2026-06-16 10:54:31 ./wreath/CN_type_20086_BNF_41767912_cn_coin_23315_o_obv.jpg
?rw------- root/root      14749 2026-06-16 10:54:31 ./wreath/CN_type_20086_MK_Platzhalter_cn_coin_45919_p_obv.jpg
?rw------- root/root      24903 2026-06-16 10:54:31 ./wreath/CN_type_20087_BNF_41767914_cn_coin_23317_o_obv.jpg
?rw------- root/root      13771 2026-06-16 10:54:31 ./wreath/CN_type_20087_MK_41767914_cn_coin_23317_p_obv.jpg
?rw------- root/root      16083 2026-06-16 10:54:31 ./wreath/CN_type_20087_MK_Platzhalter_cn_coin_45947_p_obv.jpg
?rw------- root/root       9896 2026-06-16 10:54:31 ./wreath/CN_type_2009_cn_coin_9874_p_obv.jpg
?rw------- root/root      20503 2026-06-16 10:54:31 ./wreath/CN_type_20102_BNF_41767910_cn_coin_23313_o_obv.jpg
?rw------- root/root      26494 2026-06-16 10:54:31 ./wreath/CN_type_20102_MK_18266353_cn_coin_30729_o_obv.jpg
?rw------- root/root      11961 2026-06-16 10:54:31 ./wreath/CN_type_20102_MK_18266353_cn_coin_30729_p_obv.jpg
?rw------- root/root      31118 2026-06-16 10:54:31 ./wreath/CN_type_20102_MK_18266354_cn_coin_30730_o_obv.jpg
?rw------- root/root      12442 2026-06-16 10:54:31 ./wreath/CN_type_20102_MK_41767910_cn_coin_23313_p_obv.jpg
?rw------- root/root      14774 2026-06-16 10:54:31 ./wreath/CN_type_20103_MK_Platzhalter_cn_coin_45940_p_obv.jpg
?rw------- root/root       8051 2026-06-16 10:54:31 ./wreath/CN_type_2010_cn_coin_9876_p_obv.jpg
?rw------- root/root      11810 2026-06-16 10:54:31 ./wreath/CN_type_2010_cn_coin_9877_p_obv.jpg
?rw------- root/root      10085 2026-06-16 10:54:32 ./wreath/CN_type_2012_cn_coin_9883_p_obv.jpg
?rw------- root/root      10145 2026-06-16 10:54:32 ./wreath/CN_type_2012_cn_coin_9885_p_obv.jpg
?rw------- root/root       9280 2026-06-16 10:54:32 ./wreath/CN_type_2013_cn_coin_9884_p_obv.jpg
?rw------- root/root      15371 2026-06-16 10:54:32 ./wreath/CN_type_20142_BNF_41845814_cn_coin_26194_o_obv.jpg
?rw------- root/root      17005 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_30904_p_obv.jpg
?rw------- root/root      17696 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44680_p_obv.jpg
?rw------- root/root      15144 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44681_p_obv.jpg
?rw------- root/root      15158 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44682_p_obv.jpg
?rw------- root/root      16080 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44683_p_obv.jpg
?rw------- root/root      16362 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44684_p_obv.jpg
?rw------- root/root      16615 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44685_p_obv.jpg
?rw------- root/root      17182 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44686_p_obv.jpg
?rw------- root/root      19020 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44687_p_obv.jpg
?rw------- root/root      18373 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44688_p_obv.jpg
?rw------- root/root      18533 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44689_p_obv.jpg
?rw------- root/root      17865 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44690_p_obv.jpg
?rw------- root/root      15859 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44691_p_obv.jpg
?rw------- root/root      16365 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44692_p_obv.jpg
?rw------- root/root      15573 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44693_p_obv.jpg
?rw------- root/root      15664 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44694_p_obv.jpg
?rw------- root/root      18383 2026-06-16 10:54:32 ./wreath/CN_type_20142_cn_coin_44695_p_obv.jpg
?rw------- root/root      17163 2026-06-16 10:54:32 ./wreath/CN_type_20142_MK_18269383_cn_coin_30904_o_obv.jpg
?rw------- root/root      18686 2026-06-16 10:54:32 ./wreath/CN_type_20142_MK_18269385_cn_coin_30906_o_obv.jpg
?rw------- root/root       9098 2026-06-16 10:54:32 ./wreath/CN_type_2014_cn_coin_9886_p_obv.jpg
?rw------- root/root       9203 2026-06-16 10:54:32 ./wreath/CN_type_2014_cn_coin_9887_p_obv.jpg
?rw------- root/root      10424 2026-06-16 10:54:32 ./wreath/CN_type_2014_cn_coin_9888_p_obv.jpg
?rw------- root/root       8352 2026-06-16 10:54:32 ./wreath/CN_type_2014_cn_coin_9889_p_obv.jpg
?rw------- root/root      27568 2026-06-16 10:54:32 ./wreath/CN_type_2014_MK_18239823_cn_coin_3727_o_obv.jpg
?rw------- root/root      21356 2026-06-16 10:54:32 ./wreath/CN_type_20163_MK_18284787_cn_coin_46325_o_obv.jpg
?rw------- root/root      21438 2026-06-16 10:54:33 ./wreath/CN_type_20163_MK_18284787_cn_coin_46325_o_rev.jpg
?rw------- root/root       7691 2026-06-16 10:54:33 ./wreath/CN_type_2016_cn_coin_8998_p_obv.jpg
?rw------- root/root      19450 2026-06-16 10:54:33 ./wreath/CN_type_20171_MK_18278187_cn_coin_50814_o_obv.jpg
?rw------- root/root      16957 2026-06-16 10:54:33 ./wreath/CN_type_20172_cn_coin_44521_p_rev.jpg
?rw------- root/root      16177 2026-06-16 10:54:33 ./wreath/CN_type_20172_cn_coin_44531_p_rev.jpg
?rw------- root/root      10833 2026-06-16 10:54:33 ./wreath/CN_type_2018_cn_coin_9891_p_obv.jpg
?rw------- root/root      10320 2026-06-16 10:54:33 ./wreath/CN_type_2019_cn_coin_9895_p_obv.jpg
?rw------- root/root       8820 2026-06-16 10:54:33 ./wreath/CN_type_2021_cn_coin_9898_p_obv.jpg
?rw------- root/root      10760 2026-06-16 10:54:33 ./wreath/CN_type_2021_cn_coin_9898_p_rev.jpg
?rw------- root/root      26109 2026-06-16 10:54:33 ./wreath/CN_type_2021_MK_18240133_cn_coin_3753_o_obv.jpg
?rw------- root/root      25362 2026-06-16 10:54:33 ./wreath/CN_type_2021_MK_18240133_cn_coin_3753_o_rev.jpg
?rw------- root/root      14440 2026-06-16 10:54:33 ./wreath/CN_type_20225_cn_coin_43468_p_obv.jpg
?rw------- root/root      15313 2026-06-16 10:54:33 ./wreath/CN_type_20225_cn_coin_43468_p_rev.jpg
?rw------- root/root      17921 2026-06-16 10:54:33 ./wreath/CN_type_20225_cn_coin_43469_p_obv.jpg
?rw------- root/root      17557 2026-06-16 10:54:33 ./wreath/CN_type_20225_cn_coin_43469_p_rev.jpg
?rw------- root/root      19033 2026-06-16 10:54:33 ./wreath/CN_type_20226_BNF_41825946_cn_coin_25080_o_obv.jpg
?rw------- root/root      19246 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_30923_p_obv.jpg
?rw------- root/root      19335 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_30923_p_rev.jpg
?rw------- root/root      14975 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43289_p_obv.jpg
?rw------- root/root      13899 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43289_p_rev.jpg
?rw------- root/root      16658 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43291_p_obv.jpg
?rw------- root/root      18297 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43291_p_rev.jpg
?rw------- root/root      16188 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43292_p_obv.jpg
?rw------- root/root      15342 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43292_p_rev.jpg
?rw------- root/root      18432 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43428_p_obv.jpg
?rw------- root/root      20777 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43428_p_rev.jpg
?rw------- root/root      18506 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43429_p_obv.jpg
?rw------- root/root      23677 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43429_p_rev.jpg
?rw------- root/root      15136 2026-06-16 10:54:33 ./wreath/CN_type_20229_cn_coin_43439_p_obv.jpg
?rw------- root/root      18057 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43439_p_rev.jpg
?rw------- root/root      14668 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43441_p_obv.jpg
?rw------- root/root      17969 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43441_p_rev.jpg
?rw------- root/root      16717 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43443_p_obv.jpg
?rw------- root/root      17196 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43443_p_rev.jpg
?rw------- root/root      17016 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43458_p_obv.jpg
?rw------- root/root      18636 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43458_p_rev.jpg
?rw------- root/root      15601 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43460_p_obv.jpg
?rw------- root/root      17246 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43460_p_rev.jpg
?rw------- root/root      16051 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43461_p_obv.jpg
?rw------- root/root      15888 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43461_p_rev.jpg
?rw------- root/root      19749 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43462_p_obv.jpg
?rw------- root/root      22559 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43462_p_rev.jpg
?rw------- root/root      16080 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43464_p_obv.jpg
?rw------- root/root      17526 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43464_p_rev.jpg
?rw------- root/root      17903 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43465_p_obv.jpg
?rw------- root/root      20532 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43465_p_rev.jpg
?rw------- root/root      14443 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43467_p_obv.jpg
?rw------- root/root      13586 2026-06-16 10:54:34 ./wreath/CN_type_20229_cn_coin_43467_p_rev.jpg
?rw------- root/root      22043 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269407_cn_coin_30923_o_obv.jpg
?rw------- root/root      21939 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269407_cn_coin_30923_o_rev.jpg
?rw------- root/root      18274 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269408_cn_coin_30924_o_obv.jpg
?rw------- root/root      17525 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269408_cn_coin_30924_o_rev.jpg
?rw------- root/root      22180 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269413_cn_coin_30929_o_obv.jpg
?rw------- root/root      21587 2026-06-16 10:54:34 ./wreath/CN_type_20229_MK_18269413_cn_coin_30929_o_rev.jpg
?rw------- root/root      24934 2026-06-16 10:54:34 ./wreath/CN_type_2022_cn_coin_30394_o_obv.jpg
?rw------- root/root      10190 2026-06-16 10:54:34 ./wreath/CN_type_2022_cn_coin_9899_p_obv.jpg
?rw------- root/root      14984 2026-06-16 10:54:34 ./wreath/CN_type_20230_cn_coin_30918_p_rev.jpg
?rw------- root/root      16952 2026-06-16 10:54:34 ./wreath/CN_type_20230_cn_coin_30928_p_rev.jpg
?rw------- root/root      19609 2026-06-16 10:54:34 ./wreath/CN_type_20230_cn_coin_30930_p_rev.jpg
?rw------- root/root      16753 2026-06-16 10:54:34 ./wreath/CN_type_20230_cn_coin_43290_p_rev.jpg
?rw------- root/root      19149 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43426_p_rev.jpg
?rw------- root/root      15933 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43430_p_rev.jpg
?rw------- root/root      15846 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43432_p_rev.jpg
?rw------- root/root      17882 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43446_p_rev.jpg
?rw------- root/root      15665 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43447_p_rev.jpg
?rw------- root/root      18440 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43449_p_rev.jpg
?rw------- root/root      18904 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43450_p_rev.jpg
?rw------- root/root      19457 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43451_p_rev.jpg
?rw------- root/root      21074 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43452_p_rev.jpg
?rw------- root/root      18476 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43453_p_rev.jpg
?rw------- root/root      17218 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43456_p_rev.jpg
?rw------- root/root      21712 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43457_p_rev.jpg
?rw------- root/root      18631 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43463_p_rev.jpg
?rw------- root/root      19946 2026-06-16 10:54:35 ./wreath/CN_type_20230_cn_coin_43466_p_rev.jpg
?rw------- root/root      24473 2026-06-16 10:54:35 ./wreath/CN_type_20230_MK_18269402_cn_coin_30918_o_rev.jpg
?rw------- root/root      24854 2026-06-16 10:54:35 ./wreath/CN_type_20230_MK_18269405_cn_coin_30921_o_rev.jpg
?rw------- root/root      19397 2026-06-16 10:54:35 ./wreath/CN_type_20230_MK_18269412_cn_coin_30928_o_rev.jpg
?rw------- root/root      25829 2026-06-16 10:54:35 ./wreath/CN_type_20230_MK_18269415_cn_coin_30930_o_rev.jpg
?rw------- root/root      17599 2026-06-16 10:54:35 ./wreath/CN_type_20230_MK_18269416_cn_coin_30931_o_rev.jpg
?rw------- root/root       9138 2026-06-16 10:54:35 ./wreath/CN_type_2023_cn_coin_9902_p_obv.jpg
?rw------- root/root       9481 2026-06-16 10:54:35 ./wreath/CN_type_2024_cn_coin_9903_p_obv.jpg
?rw------- root/root      15764 2026-06-16 10:54:35 ./wreath/CN_type_20254_cn_coin_47151_p_obv.jpg
?rw------- root/root      14963 2026-06-16 10:54:35 ./wreath/CN_type_20254_cn_coin_47208_p_obv.jpg
?rw------- root/root      15874 2026-06-16 10:54:35 ./wreath/CN_type_20256_cn_coin_46904_p_obv.jpg
?rw------- root/root      17637 2026-06-16 10:54:35 ./wreath/CN_type_20256_cn_coin_47193_p_obv.jpg
?rw------- root/root      18965 2026-06-16 10:54:35 ./wreath/CN_type_20256_MK_Platzhalter_cn_coin_47533_o_obv.jpg
?rw------- root/root      20976 2026-06-16 10:54:35 ./wreath/CN_type_20258_cn_coin_47185_p_obv.jpg
?rw------- root/root      16809 2026-06-16 10:54:35 ./wreath/CN_type_20259_cn_coin_47183_p_obv.jpg
?rw------- root/root      19107 2026-06-16 10:54:35 ./wreath/CN_type_20259_cn_coin_47184_p_obv.jpg
?rw------- root/root      23922 2026-06-16 10:54:36 ./wreath/CN_type_20259_MK_Platzhalter_cn_coin_47504_o_obv.jpg
?rw------- root/root      18776 2026-06-16 10:54:36 ./wreath/CN_type_20260_cn_coin_47182_p_obv.jpg
?rw------- root/root      21111 2026-06-16 10:54:36 ./wreath/CN_type_20261_BNF_41769127_cn_coin_24530_o_obv.jpg
?rw------- root/root      16523 2026-06-16 10:54:36 ./wreath/CN_type_20261_BNF_41859937_cn_coin_26604_o_obv.jpg
?rw------- root/root      16554 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47149_p_obv.jpg
?rw------- root/root      19073 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47173_p_obv.jpg
?rw------- root/root      15512 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47174_p_obv.jpg
?rw------- root/root      19967 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47175_p_obv.jpg
?rw------- root/root      18131 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47176_p_obv.jpg
?rw------- root/root      20815 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47177_p_obv.jpg
?rw------- root/root      14159 2026-06-16 10:54:36 ./wreath/CN_type_20261_cn_coin_47181_p_obv.jpg
?rw------- root/root      24615 2026-06-16 10:54:36 ./wreath/CN_type_20261_MK_Platzhalter_cn_coin_47492_o_obv.jpg
?rw------- root/root      17057 2026-06-16 10:54:36 ./wreath/CN_type_20262_cn_coin_47180_p_obv.jpg
?rw------- root/root      22410 2026-06-16 10:54:36 ./wreath/CN_type_20262_MK_Platzhalter_cn_coin_47499_o_obv.jpg
?rw------- root/root      22387 2026-06-16 10:54:36 ./wreath/CN_type_20263_BNF_41767721_cn_coin_23124_o_obv.jpg
?rw------- root/root      23993 2026-06-16 10:54:36 ./wreath/CN_type_20264_BNF_41769126_cn_coin_24529_o_obv.jpg
?rw------- root/root      16064 2026-06-16 10:54:36 ./wreath/CN_type_20264_cn_coin_24529_p_obv.jpg
?rw------- root/root      17011 2026-06-16 10:54:36 ./wreath/CN_type_20264_cn_coin_47178_p_obv.jpg
?rw------- root/root      18024 2026-06-16 10:54:36 ./wreath/CN_type_20264_cn_coin_47179_p_obv.jpg
?rw------- root/root      23071 2026-06-16 10:54:36 ./wreath/CN_type_20264_MK_Platzhalter_cn_coin_47497_o_obv.jpg
?rw------- root/root      23084 2026-06-16 10:54:36 ./wreath/CN_type_20264_MK_Platzhalter_cn_coin_47498_o_obv.jpg
?rw------- root/root      23790 2026-06-16 10:54:36 ./wreath/CN_type_20265_BNF_41769123_cn_coin_24526_o_obv.jpg
?rw------- root/root      23792 2026-06-16 10:54:36 ./wreath/CN_type_20265_BNF_41769124_cn_coin_24527_o_obv.jpg
?rw------- root/root      18296 2026-06-16 10:54:36 ./wreath/CN_type_20265_cn_coin_24527_p_obv.jpg
?rw------- root/root      17595 2026-06-16 10:54:36 ./wreath/CN_type_20265_cn_coin_47166_p_obv.jpg
?rw------- root/root      18331 2026-06-16 10:54:36 ./wreath/CN_type_20265_cn_coin_47169_p_obv.jpg
?rw------- root/root      16741 2026-06-16 10:54:36 ./wreath/CN_type_20265_cn_coin_47170_p_obv.jpg
?rw------- root/root      15569 2026-06-16 10:54:37 ./wreath/CN_type_20265_cn_coin_47171_p_obv.jpg
?rw------- root/root      24564 2026-06-16 10:54:37 ./wreath/CN_type_20265_MK_Platzhalter_cn_coin_47493_o_obv.jpg
?rw------- root/root      20296 2026-06-16 10:54:37 ./wreath/CN_type_20265_MK_Platzhalter_cn_coin_47494_o_obv.jpg
?rw------- root/root      20421 2026-06-16 10:54:37 ./wreath/CN_type_20266_BNF_41769125_cn_coin_24528_o_obv.jpg
?rw------- root/root      18860 2026-06-16 10:54:37 ./wreath/CN_type_20266_BNF_41845939_cn_coin_26319_o_obv.jpg
?rw------- root/root      18050 2026-06-16 10:54:37 ./wreath/CN_type_20266_cn_coin_47172_p_obv.jpg
?rw------- root/root      22157 2026-06-16 10:54:37 ./wreath/CN_type_20266_MK_Platzhalter_cn_coin_47495_o_obv.jpg
?rw------- root/root      23980 2026-06-16 10:54:37 ./wreath/CN_type_20266_MK_Platzhalter_cn_coin_47496_o_obv.jpg
?rw------- root/root      19449 2026-06-16 10:54:37 ./wreath/CN_type_20267_cn_coin_47165_p_obv.jpg
?rw------- root/root       9916 2026-06-16 10:54:37 ./wreath/CN_type_2026_cn_coin_9905_p_obv.jpg
?rw------- root/root      10041 2026-06-16 10:54:37 ./wreath/CN_type_2026_cn_coin_9906_p_obv.jpg
?rw------- root/root      22935 2026-06-16 10:54:37 ./wreath/CN_type_20270_BNF_41769120_cn_coin_24523_o_obv.jpg
?rw------- root/root      21957 2026-06-16 10:54:37 ./wreath/CN_type_20270_BNF_41769140_cn_coin_24543_o_obv.jpg
?rw------- root/root      16649 2026-06-16 10:54:37 ./wreath/CN_type_20270_cn_coin_24523_p_obv.jpg
?rw------- root/root      17271 2026-06-16 10:54:37 ./wreath/CN_type_20270_cn_coin_47152_p_obv.jpg
?rw------- root/root      24396 2026-06-16 10:54:37 ./wreath/CN_type_20272_BNF_41769097_cn_coin_24500_o_obv.jpg
?rw------- root/root      21119 2026-06-16 10:54:37 ./wreath/CN_type_20272_BNF_41769098_cn_coin_24501_o_obv.jpg
?rw------- root/root      17581 2026-06-16 10:54:37 ./wreath/CN_type_20272_cn_coin_24501_p_obv.jpg
?rw------- root/root      16480 2026-06-16 10:54:37 ./wreath/CN_type_20272_cn_coin_47080_p_obv.jpg
?rw------- root/root      16968 2026-06-16 10:54:37 ./wreath/CN_type_20272_cn_coin_47146_p_obv.jpg
?rw------- root/root      15068 2026-06-16 10:54:37 ./wreath/CN_type_20272_cn_coin_47147_p_obv.jpg
?rw------- root/root      23913 2026-06-16 10:54:37 ./wreath/CN_type_20273_BNF_41769105_cn_coin_24508_o_obv.jpg
?rw------- root/root      17842 2026-06-16 10:54:37 ./wreath/CN_type_20273_cn_coin_24508_p_obv.jpg
?rw------- root/root      18230 2026-06-16 10:54:37 ./wreath/CN_type_20273_cn_coin_47144_p_obv.jpg
?rw------- root/root      16126 2026-06-16 10:54:37 ./wreath/CN_type_20273_cn_coin_47145_p_obv.jpg
?rw------- root/root      20629 2026-06-16 10:54:37 ./wreath/CN_type_20273_MK_18222902_cn_coin_17870_o_obv.jpg
?rw------- root/root      25828 2026-06-16 10:54:37 ./wreath/CN_type_20274_BNF_41769100_cn_coin_24503_o_obv.jpg
?rw------- root/root      22662 2026-06-16 10:54:37 ./wreath/CN_type_20274_BNF_41769106_cn_coin_24509_o_obv.jpg
?rw------- root/root      16868 2026-06-16 10:54:37 ./wreath/CN_type_20274_cn_coin_47139_p_obv.jpg
?rw------- root/root      15741 2026-06-16 10:54:37 ./wreath/CN_type_20274_cn_coin_47141_p_obv.jpg
?rw------- root/root      14415 2026-06-16 10:54:38 ./wreath/CN_type_20274_cn_coin_47142_p_obv.jpg
?rw------- root/root      15531 2026-06-16 10:54:38 ./wreath/CN_type_20274_cn_coin_47143_p_obv.jpg
?rw------- root/root      21493 2026-06-16 10:54:38 ./wreath/CN_type_20274_MK_18222903_cn_coin_17871_o_obv.jpg

"Scraping" databases for coin images and metadata

In [ ]:
# set naming convention for extracted coin image datasets
dataset_str = "pella"
# dataset_str = "bigr"
# dataset_str = "seleucid"

BASE_URL = "https://numismatics.org/" + dataset_str + "/results?q=&start={}"
OUTPUT_DIR = OUTPUT_DIR = "/content/drive/MyDrive/coins_project"
IMAGE_DIR = os.path.join(OUTPUT_DIR, dataset_str + "_images")

# creates a directory in which to save images
os.makedirs(IMAGE_DIR, exist_ok=True)

# session for scraping/crawling
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0"
})


def parse_page(start):

    url = BASE_URL.format(start)

    r = session.get(url, timeout=30)
    r.raise_for_status()

    soup = BeautifulSoup(r.text, "html.parser")

    page_records = []

    for coin in soup.select("div.result-doc"):

        # records ID

        h4 = coin.find("h4")
        if h4 is None:
            continue

        a = h4.find("a")
        if a is None:
            continue

        record_id = a["href"].split("/")[-1]

        # gets image

        image_url = None

        thumb = coin.select_one("a.thumbImage")

        if thumb is not None:
            image_url = thumb.get("href")

        # gets metadata

        metadata = {}

        for dt, dd in zip(
            coin.find_all("dt"),
            coin.find_all("dd")
        ):
            metadata[
                dt.get_text(strip=True)
            ] = dd.get_text(" ", strip=True)

        page_records.append({

            "RecordId": record_id,

            "ImageURL": image_url,

            "Obverse": metadata.get("Obverse"),

            "Reverse": metadata.get("Reverse"),

            "Date": metadata.get("Date"),

            "Denomination": metadata.get("Denomination"),

            "Weight": metadata.get("Weight (in g)")
        })

    return page_records


# downloads image
def download_image(url, filename):

    if url is None:
        return False

    try:

        r = session.get(url, timeout=30)

        if r.status_code != 200:
            return False

        with open(filename, "wb") as f:
            f.write(r.content)

        return True

    except Exception:

        return False

records = []

TOTAL = 5000
PAGE_SIZE = 20

# crawls site
for start in tqdm(range(0, TOTAL, PAGE_SIZE)):

    page = parse_page(start)

    for coin in page:

        # downloads image
        image_name = f'{coin["RecordId"]}.jpg'

        image_path = os.path.join(
            IMAGE_DIR,
            image_name
        )

        success = download_image(
            coin["ImageURL"],
            image_path
        )

        if not success:
            image_name = None

        # stores metadata
        records.append({

            "RecordId": coin["RecordId"],

            "Image": image_name,

            "Obverse": coin["Obverse"],

            "Reverse": coin["Reverse"],

            "Date": coin["Date"],

            "Denomination": coin["Denomination"],

            "Weight": coin["Weight"]

        })

    # delay for server
    time.sleep(0.1)

# saves dataset metadata as csv
df = pd.DataFrame(records)
df.to_csv(
    os.path.join(OUTPUT_DIR, dataset_str + "_coins.csv"),
    index=False
)

print(df.head())
print()
print("Total records:", len(df))

100%|██████████| 250/250 [50:41<00:00, 12.17s/it]

            RecordId                  Image  \
0  pella.philip_ii.1                   None
1  pella.philip_ii.2  pella.philip_ii.2.jpg
2  pella.philip_ii.3                   None
3  pella.philip_ii.4  pella.philip_ii.4.jpg
4  pella.philip_ii.5  pella.philip_ii.5.jpg

                                             Obverse  \
0                     Laureate head of Zeus to right
1   Head of youth to right, hair tied with strophion
2                     Laureate head of Zeus to right
3                     Laureate head of Zeus to right
4  Head of beardless Heracles right wearing lion ...

                                             Reverse               Date  \
0  ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...  359 BCE - 348 BCE
1  ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...  359 BCE - 348 BCE
2  ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...  359 BCE - 348 BCE
3  ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...  359 BCE - 348 BCE
4  ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...  359 BCE - 348 BCE

  Denomination Weight
0  Tetradrachm   None
1   Hemidrachm   None
2  Tetradrachm   None
3  Tetradrachm   None
4     Didrachm   None

Total records: 4974

Investigates the .tar paths of coin datasets once they are saved

In [ ]:
src = Path("/content/drive/MyDrive/coins_project/" + dataset_str + "_images")  # Drive folder containing motif/image folders
tar_path = Path("/content/drive/MyDrive/coins_project/" + dataset_str + "_images.tar")

print("source:", src)
print("tar:", tar_path)

!tar -czf "$tar_path" -C "$src" .

source: /content/drive/MyDrive/coins_project/pella_images
tar: /content/drive/MyDrive/coins_project/pella_images.tar
^C

Moving on to booting up the deep learning model using a .pth file and testing it on new datasets

In [ ]:
checkpoint_path = "/content/drive/MyDrive/coins_project/coin_motif_vit_checkpoint.pth"

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu

In [ ]:
num_motifs = 7

model = timm.create_model(
    "vit_base_patch16_224.augreg_in21k",
    pretrained=False,
    num_classes=num_motifs,
)

model.to(device)

VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (patch_drop): Identity()
  (norm_pre): Identity()
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (1): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (2): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (3): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (4): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (5): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (6): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (7): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (8): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (9): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (10): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (11): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
  )
  (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (fc_norm): Identity()
  (head_drop): Dropout(p=0.0, inplace=False)
  (head): Linear(in_features=768, out_features=7, bias=True)
)

In [ ]:
checkpoint = torch.load(
    checkpoint_path,
    map_location=device,
)

In [ ]:
print(checkpoint.keys())

dict_keys(['model_name', 'model_state_dict', 'sample_motifs', 'thresholds', 'best_score'])

In [ ]:
model.load_state_dict(checkpoint["model_state_dict"])

In [ ]:
# evaluates model
model.eval()

VisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (patch_drop): Identity()
  (norm_pre): Identity()
  (blocks): Sequential(
    (0): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (1): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (2): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (3): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (4): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (5): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (6): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (7): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (8): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (9): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (10): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
    (11): Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (q_norm): Identity()
        (k_norm): Identity()
        (attn_drop): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): Identity()
      (drop_path1): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (norm): Identity()
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
      (ls2): Identity()
      (drop_path2): Identity()
    )
  )
  (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (fc_norm): Identity()
  (head_drop): Dropout(p=0.0, inplace=False)
  (head): Linear(in_features=768, out_features=7, bias=True)
)

In [ ]:
config = resolve_data_config({}, model=model)

transform = create_transform(
    **config,
    is_training=False,
)

Test testing procedure on a random image

In [ ]:
# image = Image.open("/content/drive/MyDrive/coins_project/CoinsDataset/CN_dataset_nlp_objects/bull/CN_type_1417_cn_coin_2220_p_rev.jpg").convert("RGB")
image = Image.open("/content/drive/MyDrive/coins_project/pella_images/pella.philip_ii.10.jpg").convert("RGB")

x = transform(image).unsqueeze(0).to(device)

In [ ]:
with torch.no_grad():
    logits = model(x)

probabilities = torch.softmax(logits, dim=1)

confidence, prediction = probabilities.max(dim=1)

print(prediction.item())
print(confidence.item())

6
0.999992847442627

Looks good!

Lastly, test the model on the other coin datasets

In [ ]:
base_path = Path('/content/drive/MyDrive/coins_project')

# pella_copy_path = base_path / 'pella_coins_copy.csv'
pella_csv_path = base_path / 'pella_coins.csv'
pella_images_path = base_path / 'pella_images'
bigr_csv_path = base_path / 'bigr_coins.csv'
bigr_images_path = base_path / 'bigr_images'
seleucid_csv_path = base_path / 'seleucid_coins.csv'
seleucid_images_path = base_path / 'seleucid_images'
cn_nlp_path = base_path / 'CoinsDataset' / 'CN_dataset_nlp_objects'

if base_path.is_dir():
  print(f"Found directory: {base_path}")
else:
  print(f"Directory not found at {base_path}")
for p in [pella_csv_path, bigr_csv_path, seleucid_csv_path]:
  if p.is_file():
    print(f"Found file: {p}")
  else:
    print(f"File not found at {p}")
for p in [pella_images_path, bigr_images_path, seleucid_images_path, cn_nlp_path]:
  if p.is_dir():
    print(f"Found directory: {p}")
  else:
    print(f"Directory not found at {p}")

Found directory: /content/drive/MyDrive/coins_project
Found file: /content/drive/MyDrive/coins_project/pella_coins_copy.csv
Found file: /content/drive/MyDrive/coins_project/pella_coins.csv
Found file: /content/drive/MyDrive/coins_project/bigr_coins.csv
Found directory: /content/drive/MyDrive/coins_project/pella_images
Found directory: /content/drive/MyDrive/coins_project/bigr_images
Found directory: /content/drive/MyDrive/coins_project/seleucid_images
Found directory: /content/drive/MyDrive/coins_project/CoinsDataset/CN_dataset_nlp_objects

In [ ]:
# collects all the motifs in the CN dataset and how often they appear.
# takes a few minutes to run
motifs_with_counts = {}
for motif in os.listdir(cn_nlp_path):
  p = cn_nlp_path / motif
  if p.is_dir():
    motifs_with_counts[motif] = len(os.listdir(cn_nlp_path / motif))

print(motifs_with_counts)

{'abacus': 5, 'abundantia': 3, 'acrostolium': 11, 'acroteria': 1, 'actaeon': 3, 'aegis': 432, 'aeneas': 57, 'aequitas': 180, 'agonistic_crown': 2, 'agrippa': 7, 'agrippina_minor': 2, 'alexander_iii': 145, 'altar': 1049, 'amphora': 247, 'anchialos': 2, 'anchises': 60, 'anchor': 32, 'androclus': 3, 'andromeda': 3, 'animal': 13, 'annona': 2, 'antinous': 5, 'antiochus_ii_theos': 2, 'antlers': 24, 'antonia_minor': 6, 'antoninus_pius': 892, 'anubis': 15, 'aphrodite': 65, 'apis': 35, 'aplustre': 84, 'apollo': 2774, 'apollon': 9, 'apple': 201, 'arch': 12, 'archer': 2, 'ares': 224, 'ariadne': 7, 'arm': 1907, 'armour': 38, 'arrow': 490, 'artemis': 923, 'ascanius': 57, 'asclepius': 1029, 'astragal': 6, 'athena': 4108, 'athlete': 115, 'attis': 7, 'augustus': 384, 'aulos': 1, 'bag': 3, 'barley': 49, 'base': 268, 'basin': 14, 'basket': 90, 'bear': 19, 'bee': 29, 'beehive': 6, 'belt': 4, 'berry': 82, 'biga': 125, 'bird': 49, 'boar': 144, 'board': 65, 'bonus_eventus': 102, 'boot': 138, 'bow': 1509, 'boxer': 4, 'branch': 939, 'breast': 9, 'britannicus': 13, 'bucranium': 63, 'bull': 1342, 'bun': 18, 'bust': 9423, 'byzas': 69, 'caduceus': 596, 'caligula': 25, 'cantharus': 617, 'cap': 191, 'capaneus': 8, 'capricorn': 30, 'caracalla': 2238, 'cattle': 2, 'centaur': 16, 'cerberus': 67, 'cestus': 6, 'cetus': 3, 'chain': 3, 'chair': 2, 'charis': 41, 'child': 10, 'chin': 6, 'chlamys': 352, 'cippus': 30, 'cista': 507, 'cithara': 116, 'city_gate': 104, 'city_goddess': 99, 'claudius': 67, 'cloak': 126, 'cloth': 1, 'club': 1014, 'coat': 15, 'coil': 1, 'column': 255, 'commodus': 947, 'concordia': 116, 'conifer': 1, 'corn': 1027, 'cornucopia': 1703, 'corn_wreath': 530, 'corybant': 4, 'cotyle': 23, 'crab': 15, 'crayfish': 1, 'crepidoma': 373, 'crescent': 261, 'cretan_bull': 11, 'crispina': 159, 'cross': 14, 'crown': 27, 'cubit_role': 116, 'cuirass': 5257, 'cup': 5, 'cybele': 318, 'dagger': 1, 'dardanos': 2, 'decius': 5, 'deer': 13, 'demeter': 971, 'demos': 32, 'diadem': 1455, 'diadumenian': 161, 'diomedes': 1, 'dionysus': 1455, 'disc': 17, 'discus': 19, 'dog': 82, 'dolphin': 1198, 'domitian': 209, 'domitia_longina': 19, 'door': 13, 'double_ax': 154, 'double_chiton': 182, 'drapery': 29, 'drum': 21, 'eagle': 1564, 'ear': 694, 'earring': 632, 'earth': 18, 'eirene': 1, 'elagabalus': 798, 'elephant': 6, 'emperor': 636, 'eros': 120, 'erymanthian_boar': 13, 'europa': 18, 'eurypylos': 3, 'eurystheus': 10, 'eye': 7, 'faustina_maior': 3, 'faustina_minor': 391, 'feather': 14, 'figure': 172, 'fillet': 24, 'fish': 37, 'flower': 18, 'foot': 1901, 'fox': 1, 'fruit': 143, 'gaius_caesar': 27, 'galley': 90, 'gallienus': 154, 'ganymed': 63, 'garland': 53, 'garment': 292, 'gate': 1, 'ge': 2, 'genius': 35, 'germanicus': 6, 'geta': 682, 'globe': 51, 'gold': 3, 'gordian': 735, 'gorgo': 9, 'gorgoneion': 450, 'grain': 485, 'grape': 1165, 'griffin': 1152, 'hades': 62, 'hadrian': 296, 'hair': 719, 'hammer': 2, 'hand': 4276, 'handle': 7, 'harpocrates': 26, 'he-goat': 510, 'head': 17978, 'headband': 3, 'headdress': 74, 'hebros': 93, 'hecate': 6, 'helios': 68, 'helle': 2, 'helmet': 3256, 'helmsman': 25, 'hephaestos': 30, 'hera': 159, 'heracles': 1368, 'herennius_etruscus': 2, 'herm': 60, 'hermes': 1039, 'herophile': 37, 'heros': 32, 'himation': 86, 'hind': 48, 'hippocampus': 6, 'hippolyte': 10, 'homonoia': 642, 'horn': 186, 'horse': 2445, 'hound': 172, 'human': 5, 'hydra': 8, 'hydria': 12, 'hygieia': 280, 'ibis': 1, 'iole': 1, 'isis': 118, 'ivy': 76, 'ivy_leaf': 22, 'ivy_wreath': 1166, 'jar': 10, 'javelin': 3, 'jaw': 34, 'julia_domna': 507, 'julia_mamaea': 121, 'julia_titi': 2, 'kaikos': 3, 'kalathos': 1444, 'kausia': 7, 'keroessa': 10, 'kline': 4, 'knee': 49, 'knife': 18, 'knot': 8, 'koronis': 8, 'kotys_i': 6, 'krater': 58, 'kyrbasia': 13, 'ladder': 8, 'ladon': 20, 'lamp': 14, 'lance': 23, 'laurel_branch': 40, 'laurel_tree': 298, 'laurel_wreath': 1171, 'leaf': 198, 'liberalitas': 5, 'lion': 1120, 'lion_skin': 993, 'lituus': 14, 'livia': 46, 'lizard': 14, 'lotus': 84, 'lucilla': 38, 'lucius_caesar': 19, 'lucius_verus': 161, 'lyre': 328, 'mace': 9, 'macrinus': 154, 'maenad': 33, 'maesa': 92, 'man': 709, 'mane': 200, 'mantle': 83, 'marcus_antonius': 9, 'marcus_aurelius': 539, 'marsyas': 28, 'maximinus_thrax': 55, 'maximus': 59, 'medusa': 7, 'melsas': 5, 'mestos': 3, 'military_attire': 342, 'modius': 37, 'mouth': 277, 'mural_crown': 33, 'nape': 264, 'naval_ram': 13, 'necklace': 195, 'nemean_lion': 35, 'nemesis': 234, 'nereid': 5, 'nero': 92, 'nerva': 29, 'nike': 884, 'nymph': 134, 'nymphaeum': 4, 'oak': 60, 'oak_wreath': 368, 'oar': 8, 'obelisk': 28, 'object': 65, 'octavia': 8, 'oinochoe': 75, 'oiskos': 17, 'olive': 83, 'olive-branch': 1, 'omphale': 1, 'omphalos': 170, 'ore': 3, 'ornament': 10, 'orpheus': 15, 'ostrich': 10, 'otacilia_severa': 85, 'owl': 434, 'ox': 6, 'palm': 29, 'palmette': 3, 'palm_branch': 609, 'paludamentum': 5117, 'pan': 34, 'panther': 226, 'parazonium': 66, 'paris': 2, 'patera': 2726, 'paula': 41, 'peacock': 6, 'pediment': 134, 'pedum': 19, 'pegasus': 17, 'pellet': 49, 'pelta': 10, 'pendant': 2, 'pergamos': 16, 'perinthos': 11, 'persephone': 624, 'perseus': 14, 'persian': 21, 'pertinax': 5, 'petasus': 874, 'philetairos': 345, 'philippus_arabs': 163, 'pig': 3, 'pilos': 102, 'pincer': 5, 'plant': 21, 'plautilla': 30, 'plectrum': 116, 'plinth': 5, 'plotina': 23, 'plough': 9, 'poimes': 1, 'pollux': 149, 'polos': 112, 'pontos': 4, 'poppaea': 25, 'poppy': 209, 'poseidon': 364, 'pot': 35, 'prisoner': 1, 'prize_crown': 274, 'protesilaos': 3, 'protome': 2047, 'prow': 322, 'ptolemy_iii_euergetes': 1, 'purse': 309, 'quadriga': 61, 'quiver': 641, 'radiate': 737, 'ram': 363, 'raven': 5, 'ray': 170, 'reed': 168, 'rein': 45, 'remus': 46, 'rhyton': 206, 'ribbon': 72, 'river-god': 375, 'robe': 61, 'rock': 299, 'roe': 2, 'roma': 116, 'romulus': 46, 'roof': 11, 'rooster': 351, 'rose': 17, 'rudder': 416, 'sabina': 46, 'sail': 780, 'salonina': 47, 'saloninus': 18, 'sandal': 3, 'satrap': 10, 'satyr': 62, 'scale': 206, 'scales': 183, 'scallop': 2, 'scepter': 1349, 'scroll': 27, 'selene': 8, 'septimius_severus': 1206, 'serapis': 359, 'serpent_staff': 256, 'severus_alexander': 591, 'she-wolf': 57, 'shell': 3, 'shield': 1792, 'ship': 84, 'shoulder': 962, 'sickle': 7, 'silenus': 168, 'simpulum': 15, 'simulacrum': 9, 'sistrum': 23, 'situla': 11, 'skostokos': 1, 'snake': 2401, 'soaemias': 17, 'soldier': 75, 'spear': 2311, 'sphinx': 68, 'spithridates': 6, 'spoke': 84, 'squid': 4, 'stag': 148, 'stalk': 1, 'standard': 102, 'star': 597, 'starflower': 22, 'statue': 447, 'statuette': 6, 'stefane': 159, 'step': 19, 'stern': 33, 'stick': 607, 'stone': 28, 'strap': 12, 'strymon': 3, 'stump_of_tree': 31, 'swastika': 2, 'sword': 79, 'syrinx': 2, 'table': 181, 'taenia': 783, 'telephos': 19, 'telesphorus': 113, 'temple': 613, 'thalassa': 12, 'theos_megas': 140, 'thorn': 2, 'throne': 1404, 'thronia': 1, 'thunderbolt': 383, 'thymiaterion': 40, 'thyrsus': 635, 'tiara': 9, 'tiberius': 48, 'titus': 39, 'toga': 17, 'tongue': 264, 'tonzos': 9, 'torch': 1069, 'tortoise': 1, 'tower': 559, 'trajan': 424, 'tranquillina': 226, 'trebonianus_gallus': 16, 'tree': 470, 'trident': 385, 'tripod': 618, 'triptolemos': 18, 'triskele': 18, 'triton': 10, 'trophy': 197, 'tunic': 1, 'tunny': 1133, 'turtle': 1, 'twins': 57, 'tyche': 572, 'tympanon': 129, 'umbo': 6, 'urn': 300, 'valerian': 32, 'vase': 35, 'veil': 526, 'vespasian': 55, 'vessel': 56, 'vexillum': 2, 'vine': 850, 'virtus': 8, 'volusian': 18, 'wave': 6, 'wheel': 258, 'whip': 21, 'wine_skin': 26, 'wing': 2276, 'wolf': 1, 'woman': 733, 'worm': 35, 'wreath': 12279, 'wrestler': 5, 'youth': 3, 'zeus': 1022, 'zodiac': 1}

In [ ]:
# Reduce to the most frequently appearing motifs.
# This seems to be about the cutoff in the model-training/testing file.
# That is, it's about 0.1% of the length of the CN dataset.
MIN_MOTIF_FREQUENCY = 150
frequent_motifs = {motif: count for (motif,count) in motifs_with_counts.items() if count >= MIN_MOTIF_FREQUENCY}
print(frequent_motifs)

{'aegis': 432, 'aequitas': 180, 'altar': 1049, 'amphora': 247, 'antoninus_pius': 892, 'apollo': 2774, 'apple': 201, 'ares': 224, 'arm': 1907, 'arrow': 490, 'artemis': 923, 'asclepius': 1029, 'athena': 4108, 'augustus': 384, 'base': 268, 'bow': 1509, 'branch': 939, 'bull': 1342, 'bust': 9423, 'caduceus': 596, 'cantharus': 617, 'cap': 191, 'caracalla': 2238, 'chlamys': 352, 'cista': 507, 'club': 1014, 'column': 255, 'commodus': 947, 'corn': 1027, 'cornucopia': 1703, 'corn_wreath': 530, 'crepidoma': 373, 'crescent': 261, 'crispina': 159, 'cuirass': 5257, 'cybele': 318, 'demeter': 971, 'diadem': 1455, 'diadumenian': 161, 'dionysus': 1455, 'dolphin': 1198, 'domitian': 209, 'double_ax': 154, 'double_chiton': 182, 'eagle': 1564, 'ear': 694, 'earring': 632, 'elagabalus': 798, 'emperor': 636, 'faustina_minor': 391, 'figure': 172, 'foot': 1901, 'gallienus': 154, 'garment': 292, 'geta': 682, 'gordian': 735, 'gorgoneion': 450, 'grain': 485, 'grape': 1165, 'griffin': 1152, 'hadrian': 296, 'hair': 719, 'hand': 4276, 'he-goat': 510, 'head': 17978, 'helmet': 3256, 'hera': 159, 'heracles': 1368, 'hermes': 1039, 'homonoia': 642, 'horn': 186, 'horse': 2445, 'hound': 172, 'hygieia': 280, 'ivy_wreath': 1166, 'julia_domna': 507, 'kalathos': 1444, 'laurel_tree': 298, 'laurel_wreath': 1171, 'leaf': 198, 'lion': 1120, 'lion_skin': 993, 'lucius_verus': 161, 'lyre': 328, 'macrinus': 154, 'man': 709, 'mane': 200, 'marcus_aurelius': 539, 'military_attire': 342, 'mouth': 277, 'nape': 264, 'necklace': 195, 'nemesis': 234, 'nike': 884, 'oak_wreath': 368, 'omphalos': 170, 'owl': 434, 'palm_branch': 609, 'paludamentum': 5117, 'panther': 226, 'patera': 2726, 'persephone': 624, 'petasus': 874, 'philetairos': 345, 'philippus_arabs': 163, 'poppy': 209, 'poseidon': 364, 'prize_crown': 274, 'protome': 2047, 'prow': 322, 'purse': 309, 'quiver': 641, 'radiate': 737, 'ram': 363, 'ray': 170, 'reed': 168, 'rhyton': 206, 'river-god': 375, 'rock': 299, 'rooster': 351, 'rudder': 416, 'sail': 780, 'scale': 206, 'scales': 183, 'scepter': 1349, 'septimius_severus': 1206, 'serapis': 359, 'serpent_staff': 256, 'severus_alexander': 591, 'shield': 1792, 'shoulder': 962, 'silenus': 168, 'snake': 2401, 'spear': 2311, 'star': 597, 'statue': 447, 'stefane': 159, 'stick': 607, 'table': 181, 'taenia': 783, 'temple': 613, 'throne': 1404, 'thunderbolt': 383, 'thyrsus': 635, 'tongue': 264, 'torch': 1069, 'tower': 559, 'trajan': 424, 'tranquillina': 226, 'tree': 470, 'trident': 385, 'tripod': 618, 'trophy': 197, 'tunny': 1133, 'tyche': 572, 'urn': 300, 'veil': 526, 'vine': 850, 'wheel': 258, 'wing': 2276, 'woman': 733, 'wreath': 12279, 'zeus': 1022}

In [ ]:
# Let's see what we're working with...
df = open_numismatics_data(pella_csv_path, pella_images_path)
df.head(10)

,RecordId,filename,Obverse,Reverse,Date,Denomination,image_path
1,pella.philip_ii.2,pella.philip_ii.2.jpg,"Head of youth to right, hair tied with strophion","ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Hemidrachm,/content/drive/MyDrive/coins_project/pella_ima...
3,pella.philip_ii.4,pella.philip_ii.4.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...
4,pella.philip_ii.5,pella.philip_ii.5.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Didrachm,/content/drive/MyDrive/coins_project/pella_ima...
7,pella.philip_ii.8,pella.philip_ii.8.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...
9,pella.philip_ii.10,pella.philip_ii.10.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Drachma,/content/drive/MyDrive/coins_project/pella_ima...
10,pella.philip_ii.11,pella.philip_ii.11.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...
11,pella.philip_ii.12,pella.philip_ii.12.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...
12,pella.philip_ii.13,pella.philip_ii.13.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Drachma,/content/drive/MyDrive/coins_project/pella_ima...
13,pella.philip_ii.14,pella.philip_ii.14.jpg,"Head of youth to right, hair tied with strophion","ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Hemidrachm,/content/drive/MyDrive/coins_project/pella_ima...
17,pella.philip_ii.18,pella.philip_ii.18.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...

In [ ]:
df = check_for_motifs(df, frequent_motifs.keys(), "Obverse")
df.head(20)

,RecordId,filename,Obverse,Reverse,Date,Denomination,image_path,aegis,aequitas,altar,...,tunny,tyche,urn,veil,vine,wheel,wing,woman,wreath,zeus
1,pella.philip_ii.2,pella.philip_ii.2.jpg,"Head of youth to right, hair tied with strophion","ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Hemidrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,pella.philip_ii.4,pella.philip_ii.4.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,pella.philip_ii.5,pella.philip_ii.5.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Didrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,pella.philip_ii.8,pella.philip_ii.8.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,pella.philip_ii.10,pella.philip_ii.10.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Drachma,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,pella.philip_ii.11,pella.philip_ii.11.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,pella.philip_ii.12,pella.philip_ii.12.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,pella.philip_ii.13,pella.philip_ii.13.jpg,Head of beardless Heracles right wearing lion ...,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Drachma,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,pella.philip_ii.14,pella.philip_ii.14.jpg,"Head of youth to right, hair tied with strophion","ΦΙΛΙΠΠΟΥ: Nude youth riding horse to left, rei...",359 BCE - 348 BCE,Hemidrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,pella.philip_ii.18,pella.philip_ii.18.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,pella.philip_ii.20,pella.philip_ii.20.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,pella.philip_ii.24,pella.philip_ii.24.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,pella.philip_ii.25,pella.philip_ii.25.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,pella.philip_ii.26,pella.philip_ii.26.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,pella.philip_ii.28,pella.philip_ii.28.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Philip II wearing causia, tunic, and...",359 BCE - 348 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,pella.philip_ii.31,pella.philip_ii.31.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to right, re...",348 BCE - 329 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
31,pella.philip_ii.32,pella.philip_ii.32.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to right, re...",348 BCE - 329 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
32,pella.philip_ii.33,pella.philip_ii.33.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to right, re...",348 BCE - 329 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,pella.philip_ii.34,pella.philip_ii.34.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to right, re...",348 BCE - 329 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
34,pella.philip_ii.35,pella.philip_ii.35.jpg,Laureate head of Zeus to right,"ΦΙΛΙΠΠΟΥ: Nude youth riding horse to right, re...",348 BCE - 329 BCE,Tetradrachm,/content/drive/MyDrive/coins_project/pella_ima...,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
motif_counts = df[frequent_motifs.keys()].sum()
motif_counts[motif_counts >= 5]

apollo        74
athena       459
bow           65
diadem        23
ear         3015
griffin       48
hair          48
head        3261
helmet       459
hera        2522
heracles    2522
lion        2522
owl           65
shield        43
snake          7
taenia         9
wreath        62
zeus         133
dtype: int64

In [ ]:
test_df = df.copy()

sample_motifs = ["eagle", "throne", "snake", "bull", "horse", "star", "head"]

data_config = resolve_model_data_config(model)
eval_tfms = create_transform(**data_config, is_training=False)

test_ds = CoinMotifDataset(test_df, sample_motifs, eval_tfms)

batch_size = 32

test_loader = DataLoader(
    test_ds,
    batch_size=batch_size,
    shuffle=False,
    num_workers=0,
    pin_memory=True,
)

In [ ]:
test_probs, test_y = predict(
    model=model,
    loader=test_loader,
    device=device,
    desc="Test",
)

for j, motif in enumerate(sample_motifs):
    positives = int(test_y[:, j].sum())

    if positives > 0:
        ap = average_precision_score(test_y[:, j], test_probs[:, j])
        print(f"{motif}: AP={ap:.4f}, positives={positives}")
    else:
        print(f"{motif}: AP=undefined, positives=0")

Test:   0%|          | 0/104 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

eagle: AP=undefined, positives=0
throne: AP=undefined, positives=0
snake: AP=0.0103, positives=7
bull: AP=undefined, positives=0
horse: AP=undefined, positives=0
star: AP=undefined, positives=0
head: AP=0.9999, positives=3261

Results of testing model on Corpus Nummorum Greco-Roman coins as well as Numismatics PELLA/BIGR/Seleucid coins

In [ ]:
# # CORPUS NUMMORUM (mAP = 0.824)
# eagle: AP=0.7564, positives=317
# throne: AP=0.8305, positives=281
# snake: AP=0.7304, positives=479
# bull: AP=0.8280, positives=265
# horse: AP=0.8858, positives=493
# star: AP=0.8288, positives=122
# head: AP=0.9110, positives=3612

In [ ]:
# # BIGR (mAP = 0.384)
# eagle: AP=0.0588, positives=1
# throne: AP=0.4306, positives=3
# snake: AP=undefined, positives=0
# bull: AP=0.1115, positives=49
# horse: AP=1.0000, positives=3
# star: AP=0.1102, positives=2
# head: AP=0.5916, positives=75

In [ ]:
# # PELLA (mAP = 0.505)
# eagle: AP=undefined, positives=0
# throne: AP=undefined, positives=0
# snake: AP=0.0103, positives=7
# bull: AP=undefined, positives=0
# horse: AP=undefined, positives=0
# star: AP=undefined, positives=0
# head: AP=0.9999, positives=3289

In [ ]:
# # SELEUCID (mAP = 0.386)
# eagle: AP=undefined, positives=0
# throne: AP=0.8209, positives=13
# snake: AP=undefined, positives=0
# bull: AP=0.0349, positives=9
# horse: AP=0.1120, positives=10
# star: AP=0.0107, positives=10
# head: AP=0.9533, positives=1062